# Generated by Django 2.1.7 on 2019-04-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo_main', '0013_auto_20181117_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('emp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(default='None', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(help_text='Minimum of 8 Characters', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('ques_1_id', models.CharField(max_length=5)),
                ('ans_1', models.CharField(max_length=50)),
                ('ques_2_id', models.CharField(max_length=5)),
                ('ans_2', models.CharField(max_length=50)),
            ],
        ),
    ]
