# Generated by Django 2.1.7 on 2019-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_auth', '0002_auto_20190415_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('authid', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('Pancard', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Database1',
        ),
    ]
