# Generated by Django 2.1.7 on 2019-04-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_auth', '0003_auto_20190415_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstDB1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Crop', models.CharField(max_length=50)),
                ('Org', models.FloatField()),
                ('Pred', models.FloatField()),
            ],
        ),
    ]
